// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9yKLud950sn3PLAjlQRX2NzoxoTPhifI',
    appId: '1:317699462487:web:d7bdcbeda1a2b3c3a45a12',
    messagingSenderId: '317699462487',
    projectId: 'chat-app-6bcb1',
    authDomain: 'chat-app-6bcb1.firebaseapp.com',
    storageBucket: 'chat-app-6bcb1.appspot.com',
    measurementId: 'G-GWSVWZZYDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAykSj1ecmDszviFJB2NQvyrr9SZO3uPBg',
    appId: '1:317699462487:android:9a1b0a14a77430e8a45a12',
    messagingSenderId: '317699462487',
    projectId: 'chat-app-6bcb1',
    storageBucket: 'chat-app-6bcb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwo0r4owPg5iSxZmcTZJGd1UY-qe6mjA',
    appId: '1:317699462487:ios:f2e8ebbe4a53ff9aa45a12',
    messagingSenderId: '317699462487',
    projectId: 'chat-app-6bcb1',
    storageBucket: 'chat-app-6bcb1.appspot.com',
    iosBundleId: 'com.example.testFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwo0r4owPg5iSxZmcTZJGd1UY-qe6mjA',
    appId: '1:317699462487:ios:f2e8ebbe4a53ff9aa45a12',
    messagingSenderId: '317699462487',
    projectId: 'chat-app-6bcb1',
    storageBucket: 'chat-app-6bcb1.appspot.com',
    iosBundleId: 'com.example.testFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9yKLud950sn3PLAjlQRX2NzoxoTPhifI',
    appId: '1:317699462487:web:b2bf9a8a17bba935a45a12',
    messagingSenderId: '317699462487',
    projectId: 'chat-app-6bcb1',
    authDomain: 'chat-app-6bcb1.firebaseapp.com',
    storageBucket: 'chat-app-6bcb1.appspot.com',
    measurementId: 'G-BDXXQ6ZC4L',
  );
}
